### ISSUE TITLE
Improve documentation clarity re 'reading' of JS Hint options

### ISSUE THREAD

**Issue by ultrawebsites** [oxyc/grunt-lint-inline#15]
The documentation on https://www.npmjs.com/package/grunt-lint-inline says that "JSHint options will be read exactly the same as the JSHint task with a few additions."

Does this mean that you can you use exact duplicates of the JS Hint options, and they will be read the same; or does this mean that you can omit all of your 'Lint Inline' options, assuming they are the same as the JS Hint options, because the actual options for JS Hint will be read?

**Comment by ultrawebsites** [comment]
So I've finally got around to playing with this, and evidently it the answer is that the JS Hint options will be read and used. 

So suggest you change the documentation, so that instead of saying "JSHint options will be read exactly the same as the JSHint task with a few additions."

Make it say something like: 
"The options set for JS Hint will be used by inline-lint when linting your (inline) JS. Inline-lint uses it's own settings to override the necessary settings - such as which files to lint (.html files).

**Comment by tolu** [comment]
I agree that the readme is not entirely clear about the usage of jsHint-options.
As you've probably seen in the source all options defined in the task will be passed on to jsHint, except the ones defined under _Additional Options_, i.e. `patterns`.
As for source files, we treat them exactly as other tasks.

What do you thing about making this change: (with example)
- - -
All options defined in the task will be passed on to JSHint with the exception of those defined under [Additional Options](#options).

```js
grunt.initConfig({
  inlinelint: {
    options: { /* options here */ }
    html: ['**/*.html'],
    php: {
      src: ['**/*.php'],
      options: { /* php-task-specific options here */ }
    }
  }
});
```
- - -

**Comment by ultrawebsites** [comment]
That would be great! Although I suggest you change the word 'defined' to 'listed', or similar (as it sounds like it is referring to the task definition options otherwise). 

I hadn't actually gone through the source code (not up to speed with Grunt task definitions at this point), and FYI I had originally got the impression that when you say "All options defined in the task will be passed on to JSHint" - I had interpreted the reference to 'JSHint' in that sentence to be referring to the 'jshint' target/task definition in my Gruntfile.js, as opposed to the JSHint linter itself - and I had thought that, given that I think most people who use this task will have a 'jshint' task in their gruntfile as well, that this task actually read the options specified for the 'jshint' task. ie. inherited from it (goes to show how much I know (I guess by definition it can't read options from other tasks?)).

PS. Sorry for the slow response, I was OS.
