### ISSUE TITLE
Warning: Cannot define property:4, object is not extensible

### ISSUE THREAD

**Issue by tamsler** [oxyc/grunt-lint-inline#16]
I updated from node 0.10.x to 0.12.x and getting the following error/warning when running:

```javascript
inlinelint: {
    html: ['app/elements/**/*.html']
}
```

Warning: Cannot define property:4, object is not extensible

inlinelint version: 0.4.3

**Comment by tolu** [comment]
Also noticed this quite recently - appears to be due to changes made between node 0.11.8 and 0.11.9 which made the following throw an error.
```js
Array.prototype.pop.apply("abcde")
```

The error is caused by version 0.0.5 of temporary so I'm updating the reference to 0.0.8 which should solve the problem.

Thanks for the heads up!

**Comment by tamsler** [comment]
Thank you for the fix.
